<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>name</key>
<string>TODO</string>
<key>scopeName</key>
<string>text.todo</string>
<key>fileTypes</key>
<array>
<string>todo</string>
</array>
<key>uuid</key>
<string>71393561-0cbc-44fa-a6aa-565c2ff3d2e8</string>
<key>ticket</key>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.block.todo</string>
<key>comment</key>
<string>TODO container</string>
<key>begin</key>
<string>^(?i:TODO):</string>
<key>beginCaptures</key>
<dict>
<key>0</key>
<dict>
<key>name</key>
<string>meta.todo.block</string>
</dict>
</dict>
<key>end</key>
<string>^:(?i:TODO).*\n</string>
<key>endCaptures</key>
<dict>
<key>0</key>
<dict>
<key>name</key>
<string>meta.todo.block</string>
</dict>
</dict>
<key>patterns</key>
<array>
<dict>
<key>include</key>
<string>$self</string>
</dict>
<dict>
<key>name</key>
<string>todo.important</string>
<key>comment</key>
<string>Important task</string>
<key>begin</key>
<string>^\s*(\!)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.important</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.open</string>
<key>comment</key>
<string>Open task</string>
<key>begin</key>
<string>^\s*(\-)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.open</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.uncertain</string>
<key>comment</key>
<string>Questionable task</string>
<key>begin</key>
<string>^\s*(\?)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.uncertain</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.ongoing</string>
<key>comment</key>
<string>Ongoing task</string>
<key>begin</key>
<string>^\s*(o)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.ongoing</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.blocked</string>
<key>comment</key>
<string>Blocked task</string>
<key>begin</key>
<string>^\s*(\/)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.blocked</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.done</string>
<key>comment</key>
<string>Done task</string>
<key>begin</key>
<string>^\s*(x)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.done</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.impossible</string>
<key>comment</key>
<string>Impossible task</string>
<key>begin</key>
<string>^\s*(\#)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.impossible</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.block.comp</string>
<key>comment</key>
<string>Comparison container</string>
<key>begin</key>
<string>^(?i:COMP):</string>
<key>beginCaptures</key>
<dict>
<key>0</key>
<dict>
<key>name</key>
<string>meta.todo.block</string>
</dict>
</dict>
<key>end</key>
<string>^:(?i:COMP).*\n</string>
<key>endCaptures</key>
<dict>
<key>0</key>
<dict>
<key>name</key>
<string>meta.todo.block</string>
</dict>
</dict>
<key>patterns</key>
<array>
<dict>
<key>include</key>
<string>$self</string>
</dict>
<dict>
<key>name</key>
<string>todo.positive</string>
<key>comment</key>
<string>Positive argument</string>
<key>begin</key>
<string>^\s*(\+)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.positive</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.negative</string>
<key>comment</key>
<string>Negative argument</string>
<key>begin</key>
<string>^\s*(\-)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.negative</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
<dict>
<key>name</key>
<string>todo.neutral</string>
<key>comment</key>
<string>Neutral argument</string>
<key>begin</key>
<string>^\s*(o)[\t ]</string>
<key>beginCaptures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.todo.neutral</string>
</dict>
</dict>
<key>end</key>
<string>\n</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>todo.ticket</string>
<key>match</key>
<string>#\d+</string>
<key>comment</key>
<string>Ticket numbers</string>
</dict>
</array>
</dict>
</array>
</dict>
</array>
</dict>
</plist>
